name: flutter_liveness
description: "Flutter plugin for liveness detection"
version: 0.0.1+1
homepage: https://github.com/knottx/flutter_liveness
repository: https://github.com/knottx/flutter_liveness
issue_tracker: https://github.com/knottx/flutter_liveness/issues
topics: [liveness, detection, face, tflite]
funding: [https://github.com/sponsors/knottx]

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  image: ">=4.5.4 <5.0.0"
  tflite_flutter: ">=0.12.1 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/models/
